spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        temp:
           # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
           use_jdbc_metadata_defaults: false
        # Because detection is disabled you have to set correct dialect by hand.
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/gofundme
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/gofundme
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
app:
#  jwt:
#    header: Authentication
#    secret: K&Mcq(\*cy(<9bUa)|E'(@]G$ao~'Vm1h@upwRWECrLvw~>M1J{26}g6ZAr;2}i
#    expiration: 86400
#    timeOfUsing: 120 # 2 hours
  image:
    userLogoSize: 2000000
  origin:
    url: http://app.donate.com
  http:
      multipart:
        enabled: true
        max-file-size: 50Mb
        max-request-size: 50Mb
paypal:
   mode: sandbox